---

- name: create directories for ember caluma portal installation
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ ember_docroot }}"

- name: copy ember caluma portal webroot to apache docroot
  synchronize:
    src: "{{ camac_releasedir }}/camac/{{ item.src }}"
    dest: "{{ item.dest }}"
    delete: yes
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - src: "ember-caluma-portal/"
      dest: "{{ ember_docroot }}"

- name: render ember patch script
  template:
    src: patch-ember-portal.sh.j2
    dest: "{{ ember_docroot }}/patch-ember-portal.sh"
    mode: "700"

- name: fix ember oidc configuration
  shell: "{{ ember_docroot }}/patch-ember-portal.sh"

- name: fix permission on basedir
  file:
    path: "{{ ember_basedir }}"
    owner: "{{ ember_apache_user }}"
