---

- name: create directories for ember caluma portal installation
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ ember_docroot }}"

- name: copy ember caluma portal webroot to apache docroot
  synchronize:
    src: "{{ camac_releasedir }}/camac/{{ item.src }}"
    dest: "{{ item.dest }}"
    delete: yes
    rsync_opts: "{{ item.rsync_opts | d() }}"
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - src: "ember-caluma-portal/"
      dest: "{{ ember_docroot }}"
