---
# tasks file for camac

- name: load customer specific variables
  include_vars:
    file: "{{ camac_customer_variables }}"
  when: camac_customer_variables != ""

- include: keycloak.yml
  when: camac_keycloak_enable

- name: create download dir for releases
  file:
    state: directory
    path: "{{ camac_releasedir }}/camac"

- name: download camac release tarball
  get_url:
    url: "{{ camac_release }}"
    dest: "{{ camac_tarball }}"
    checksum: "{% if camac_tarball_checksum %}sha256:{{ camac_tarball_checksum }}{% endif %}"

- name: unpack camac tarball
  unarchive:
    src: "{{ camac_tarball }}"
    dest: "{{ camac_releasedir }}/camac"
    remote_src: "{{ camac_unarchive_remote_src }}"

- name: create directories for camac installation
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ camac_docroot }}"

- name: copy camac webroot to apache docroot
  synchronize:
    src: "{{ camac_releasedir }}/camac/{{ item.src }}"
    dest: "{{ item.dest }}"
    delete: yes
    rsync_opts: "{{ item.rsync_opts | d() }}"
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - src: "camac/public/"
      dest: "{{ camac_docroot }}"
    - src: "camac/"
      dest: "{{ camac_libdir }}"
    - src: "configuration/"
      dest: "{{ camac_confdir }}"

- name: copy CA chain to config path
  copy:
    content: "{{ camac_ca_chain }}"
    dest: "{{ camac_confdir }}/ca.pem"
  when: camac_ca_chain | d(false)

- name: configure php for CA chain
  copy:
    content: |
      ; config for camac CA chain
      openssl.cafile = "{{ camac_confdir }}/ca.pem"
    dest: "/etc/php/7.0/apache2/conf.d/99-quovadis-ssl-chain.ini"
  when: camac_ca_chain | d(false)

- name: prepare php prepend file
  copy:
    content: |
      <?php
      define('APPLICATION_PATH', '{{ camac_libdir }}/application');
      define('APPLICATION_ENV', '{{ camac_env }}');
      {% if camac_mock_tls %}
      $_SERVER['HTTPS'] = true;
      {% endif %}
    dest: "{{ camac_confdir }}/prepend.php"

- name: ensure public configuration symlink points to actual config directory
  file:
    state: link
    src: "{{ camac_confdir }}/public"
    path: "{{ camac_docroot }}/public"

- name: ensure application configuration symlink points to actual config directory
  file:
    state: link
    src: "{{ camac_confdir }}"
    dest: "{{ camac_libdir }}/configuration"

- name: make mpdf tmp dir writable
  file:
    state: directory
    owner: "{{ camac_apache_user }}"
    dest: "{{ item }}"
  with_items:
    - "{{ camac_tmpdir }}/mpdf"
    - "{{ camac_logdir }}"

- name: configure camac php app
  template:
    dest: "{{ item }}"
    src: "application.ini.j2"
  with_items:
    - "{{ camac_confdir }}/configs/application.local.ini"

- name: install camac django app
  pip:
    name: "{{ camac_releasedir }}/camac/django/"
    extra_args: "--upgrade"

- name: run camac migrations
  shell: django-admin migrate
  environment:
    DJANGO_SETTINGS_MODULE: "camac.settings"
    DJANGO_DATABASE_ENGINE: "django.db.backends.postgresql_psycopg2"
    DJANGO_DATABASE_NAME: "{{ camac_db_dbname }}"
    DJANGO_DATABASE_USER: "{{ camac_db_username }}"
    DJANGO_DATABASE_PASSWORD: "{{ camac_db_password }}"
    DJANGO_DATABASE_HOST: "{{ camac_db_host }}"
    DJANGO_DATABASE_PORT: "{{ camac_db_port }}"

- name: load initial camac data
  shell: "python {{ camac_releasedir }}/camac/django/manage.py loadconfig"
  when: camac_load_data
  environment:
    DJANGO_SETTINGS_MODULE: "camac.settings"
    DJANGO_DATABASE_ENGINE: "django.db.backends.postgresql_psycopg2"
    DJANGO_DATABASE_NAME: "{{ camac_db_dbname }}"
    DJANGO_DATABASE_USER: "{{ camac_db_username }}"
    DJANGO_DATABASE_PASSWORD: "{{ camac_db_password }}"
    DJANGO_DATABASE_HOST: "{{ camac_db_host }}"
    DJANGO_DATABASE_PORT: "{{ camac_db_port }}"

- name: remove tmp staging dir
  file:
    state: absent
    dest: "{{ camac_releasedir }}/camac/"
