---

- name: load customer specific variables
  include_vars:
    file: "{{ camac_customer_variables }}"
  when: camac_customer_variables != ""

- include: keycloak.yml
  when: camac_keycloak_enable

- name: create download dir for releases
  file:
    state: directory
    path: "{{ camac_releasedir }}/camac"

- name: create tarball dir
  file:
    state: directory
    path: "{{ camac_tarballdir }}"

- name: download camac release tarball
  get_url:
    url: "{{ camac_release }}"
    dest: "{{ camac_tarball }}"
    checksum: "{% if camac_tarball_checksum %}sha256:{{ camac_tarball_checksum }}{% endif %}"

- name: unpack camac tarball
  unarchive:
    src: "{{ camac_tarball }}"
    dest: "{{ camac_releasedir }}/camac"
    remote_src: "{{ camac_unarchive_remote_src }}"

- include: php.yml

- include: caluma.yml
  tags: caluma

- include: python.yml
  tags: python

- name: remove tmp staging dir
  file:
    state: absent
    dest: "{{ camac_releasedir }}/camac/"
