---
# handlers file for camac

- name: restart wildfly
  service:
    name: wildfly
    state: restarted

- name: restart caluma
  service:
    name: caluma
    state: restarted

- name: restart camac api
  service:
    name: camac-api
    state: restarted
